a = input("Digite Algo:")
print("O tipo Primitivo desse valor é:", type(a))
print("So tem espaço", a.isspace())
print("É um Numero", a.isnumeric())
print("É alfabetico", a.isalpha())
print("É alfanumerico", a.isalnum())
print("Esta em maiusculo", a.isupper())
print("Esta em minusculo", a.islower())
print("Esta capitalizado", a.istitle())
